import {
  bgWhite,
  primaryButton,
  textDarkGrey,
  textLightGrey,
  textValidation,
  textWhite,
} from "@/Constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  headingText: {
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 19.2,
    paddingLeft: 24,
    paddingTop: 26,
  },
  messageText: {
    width: 326,
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 20.8,
    color: textDarkGrey,
    paddingLeft: 24,
    paddingTop: 8,
  },
  transferOwnerShipView: {
    flexDirection: "row",
    marginVertical: 8,
    marginHorizontal: 16,
    width: "88%",
    borderRadius: 5,
    padding: 16,
    backgroundColor: bgWhite,
    marginLeft: 24,
    marginTop: 16,
    shadowColor: textLightGrey,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.7,
    elevation: 1,
    height: 134,
    flexDirection: "row",
  },
  lastLoginStatusText: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 18.2,
    paddingLeft: 8,
    color: textDarkGrey,
    width: 239,
  },
  img: {
    height: 40,
    width: 40,
  },
  btn: {
    height: 32,
    width: 134,
    backgroundColor: primaryButton,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  btnText: {
    fontWeight: "600",
    fontSize: 10,
    lineHeight: 12.18,
    color: textWhite,
  },
  storeStaffView: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 9,
  },
  descText: {
    width: 200,
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 20.8,
    color: textDarkGrey,
  },
  addBtn: {
    height: 32,
    width: 97,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: primaryButton,
  },
  addBtnText: {
    color: textWhite,
    fontWeight: "600",
    fontSize: 10,
    lineHeight: 12.18,
  },
  itemView: {
    flexDirection: "row",
    marginVertical: 8,
    marginHorizontal: 16,
    width: "88%",
    borderRadius: 5,
    padding: 16,
    backgroundColor: bgWhite,
    marginLeft: 24,
    marginTop: 16,
    shadowColor: textLightGrey,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.7,
    elevation: 1,
    height: 101,
  },
  logo: {
    height: 40,
    width: 40,
  },
  title: {
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 16.8,
    paddingLeft: 8,
  },
  limitedAccessTextView: {
    height: 24,
    width: 96,
    backgroundColor: "rgba(240, 143, 33, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  accessText: {
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    color: textValidation,
  },
  detail: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 18.2,
    color: textDarkGrey,
    marginVertical: 8,
  },
  itemDataInnerView: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cancel: {
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 14.62,
    color: primaryButton,
    paddingLeft: "44%",
    paddingTop: 16,
  },
  saveBtnView: {
    marginTop: 24,
  },
});
